const huntItems = {
  weapons: [
    {category: 'weapons', name: 'Bomb Lance', size: 'large'},
    {category: 'weapons', name: 'Bornheim No. 3 Extended', size: 'small'},
    {category: 'weapons', name: 'Bornheim No. 3 Match', size: 'medium'},
    {category: 'weapons', name: 'Bornheim No. 3', size: 'small'},
    {category: 'weapons', name: 'Caldwell Conversion Chain Pistol', size: 'small'},
    {category: 'weapons', name: 'Caldwell Conversion Pistol', size: 'small'},
    {category: 'weapons', name: 'Caldwell Conversion Uppercut', size: 'small'},
    {category: 'weapons', name: 'Caldwell Pax Claw', size: 'small'},
    {category: 'weapons', name: 'Caldwell Pax', size: 'small'},
    {category: 'weapons', name: 'Caldwell Rival 78 Handcannon', size: 'medium'},
    {category: 'weapons', name: 'Caldwell Rival 78', size: 'large'},
    {category: 'weapons', name: 'Cavalry Saber', size: 'medium'},
    {category: 'weapons', name: 'Crossbow', size: 'large'},
    {category: 'weapons', name: 'Crown & King Auto-5', size: 'large'},
    {category: 'weapons', name: 'Dolch 96 Precision', size: 'medium'},
    {category: 'weapons', name: 'Dolch 96', size: 'medium'},
    {category: 'weapons', name: 'Hand Crossbow', size: 'small'},
    {category: 'weapons', name: 'Lebel 1886 Marksman', size: 'large'},
    {category: 'weapons', name: 'Lebel 1886 Talon', size: 'large'},
    {category: 'weapons', name: 'Lebel 1886', size: 'large'},
    {category: 'weapons', name: 'Machete', size: 'small'},
    {category: 'weapons', name: 'Martini-Henry IC1 Deadeye', size: 'large'},
    {category: 'weapons', name: 'Martini-Henry IC1 Marksman', size: 'large'},
    {category: 'weapons', name: 'Martini-Henry IC1 Riposte', size: 'large'},
    {category: 'weapons', name: 'Martini-Henry IC1', size: 'large'},
    {category: 'weapons', name: 'Mosin-Nagant M1891 Avtomat', size: 'large'},
    {category: 'weapons', name: 'Mosin-Nagant M1891 Bayonet', size: 'large'},
    {category: 'weapons', name: 'Mosin-Nagant M1891 Obrez Drum', size: 'medium'},
    {category: 'weapons', name: 'Mosin-Nagant M1891 Obrez Mace', size: 'medium'},
    {category: 'weapons', name: 'Mosin-Nagant M1891 Obrez', size: 'medium'},
    {category: 'weapons', name: 'Mosin-Nagant M1891 Sniper', size: 'large'},
    {category: 'weapons', name: 'Mosin-Nagant M1891', size: 'large'},
    {category: 'weapons', name: 'Nagant M1895 Deadeye', size: 'small'},
    {category: 'weapons', name: 'Nagant M1895 Officer Brawler', size: 'small'},
    {category: 'weapons', name: 'Nagant M1895 Officer Carbine Deadeye', size: 'large'},
    {category: 'weapons', name: 'Nagant M1895 Officer Carbine', size: 'large'},
    {category: 'weapons', name: 'Nagant M1895 Officer', size: 'small'},
    {category: 'weapons', name: 'Nagant M1895 Precision', size: 'medium'},
    {category: 'weapons', name: 'Nagant M1895 Silencer', size: 'small'},
    {category: 'weapons', name: 'Nagant M1895', size: 'small'},
    {category: 'weapons', name: 'Nitro Express Rifle', size: 'large'},
    {category: 'weapons', name: 'Romero 77 Handcannon', size: 'medium'},
    {category: 'weapons', name: 'Romero 77 Hatchet', size: 'medium'},
    {category: 'weapons', name: 'Romero 77 Talon', size: 'large'},
    {category: 'weapons', name: 'Romero 77', size: 'large'},
    {category: 'weapons', name: 'Sparks LRR Silencer', size: 'large'},
    {category: 'weapons', name: 'Sparks LRR Sniper', size: 'large'},
    {category: 'weapons', name: 'Sparks LRR', size: 'large'},
    {category: 'weapons', name: 'Sparks LRR', size: 'large', legendary: 'The Reckoning'},
    {category: 'weapons', name: 'Specter 1882 Bayonet', size: 'large'},
    {category: 'weapons', name: 'Specter 1882 Compact', size: 'medium'},
    {category: 'weapons', name: 'Specter 1882', size: 'large'},
    {category: 'weapons', name: 'Springfield 1866 Compact Deadeye', size: 'medium'},
    {category: 'weapons', name: 'Springfield 1866 Compact Striker', size: 'medium'},
    {category: 'weapons', name: 'Springfield 1866 Compact', size: 'medium'},
    {category: 'weapons', name: 'Springfield 1866 Marksman', size: 'large'},
    {category: 'weapons', name: 'Springfield 1866', size: 'large'},
    {category: 'weapons', name: 'Vetterli 71 Karabiner Bayonet', size: 'large'},
    {category: 'weapons', name: 'Vetterli 71 Karabiner Deadeye', size: 'large'},
    {category: 'weapons', name: 'Vetterli 71 Karabiner', size: 'large'},
    {category: 'weapons', name: 'Winfield 1887 Terminus Handcannon', size: 'medium'},
    {category: 'weapons', name: 'Winfield 1887 Terminus', size: 'large'},
    {category: 'weapons', name: 'Winfield M1873 Aperture', size: 'large'},
    {category: 'weapons', name: 'Winfield M1873 Musket Bayonet', size: 'large'},
    {category: 'weapons', name: 'Winfield M1873 Swift', size: 'large'},
    {category: 'weapons', name: 'Winfield M1873 Talon', size: 'large'},
    {category: 'weapons', name: 'Winfield M1873', size: 'large'},
    {category: 'weapons', name: 'Winfield M1873C Marksman', size: 'large'},
    {category: 'weapons', name: 'Winfield M1873C Silencer', size: 'large'},
    {category: 'weapons', name: 'Winfield M1873C Vandal Deadeye', size: 'medium'},
    {category: 'weapons', name: 'Winfield M1873C Vandal Striker', size: 'medium'},
    {category: 'weapons', name: 'Winfield M1873C Vandal', size: 'medium'},
    {category: 'weapons', name: 'Winfield M1873C', size: 'large'},
    {category: 'weapons', name: 'Winfield M1876 Centennial Sniper', size: 'large'},
    {category: 'weapons', name: 'Winfield M1876 Centennial', size: 'large'},
  ],
  tools: [
    {category: 'tools', name: 'Alert Trip Mine'},
    {category: 'tools', name: 'Blank Fire Decoys'},
    {category: 'tools', name: 'Chaos Bomb'},
    {category: 'tools', name: 'Choke Bomb'},
    {category: 'tools', name: 'Concertina Trip Mine'},
    {category: 'tools', name: 'Decoy Fuses'},
    {category: 'tools', name: 'Decoys'},
    {category: 'tools', name: 'Dusters'},
    {category: 'tools', name: 'Electric Lamp'},
    {category: 'tools', name: 'First Aid Kit'},
    {category: 'tools', name: 'Flare Pistol'},
    {category: 'tools', name: 'Fusees'},
    {category: 'tools', name: 'Heavy Knife'},
    {category: 'tools', name: 'Knife'},
    {category: 'tools', name: 'Knuckle Knife'},
    {category: 'tools', name: 'Poison Trip Mine'},
    {category: 'tools', name: 'Quad Derringer'},
    {category: 'tools', name: 'Spyglass'},
    {category: 'tools', name: 'Throwing Knives'},
  ],
  consumables: [
    {category: 'consumables', name: 'Ammo Box'},
    {category: 'consumables', name: 'Antidote Shot'},
    {category: 'consumables', name: 'Big Dynamite Bundle'},
    {category: 'consumables', name: 'Chaos Bomb'},
    {category: 'consumables', name: 'Concertina Bomb'},
    {category: 'consumables', name: 'Dynamite Bundle'},
    {category: 'consumables', name: 'Dynamite Stick'},
    {category: 'consumables', name: 'Fire Bomb'},
    {category: 'consumables', name: 'Flash Bomb'},
    {category: 'consumables', name: 'Frag Bomb'},
    {category: 'consumables', name: 'Hellfire Bomb'},
    {category: 'consumables', name: 'Hive Bomb'},
    {category: 'consumables', name: 'Liquid Fire Bomb'},
    {category: 'consumables', name: 'Poison Bomb'},
    {category: 'consumables', name: 'Stamina Shot'},
    {category: 'consumables', name: 'Sticky Bomb'},
    {category: 'consumables', name: 'Vitality Shot'},
    {category: 'consumables', name: 'Waxed Dynamite Stick'},
    {category: 'consumables', name: 'Weak Antidote Shot'},
    {category: 'consumables', name: 'Weak Stamina Shot'},
    {category: 'consumables', name: 'Weak Vitality Shot'},
  ],
};
